insert into Aircraft (aid, aname, cruisingrange) values (1, 'United', 7025);
insert into Aircraft (aid, aname, cruisingrange) values (2, 'United', 3837);
insert into Aircraft (aid, aname, cruisingrange) values (3, 'United', 4362);
insert into Aircraft (aid, aname, cruisingrange) values (4, 'Air China', 1717);
insert into Aircraft (aid, aname, cruisingrange) values (5, 'Jet Airways', 1243);
insert into Aircraft (aid, aname, cruisingrange) values (6, 'Jet Airways', 2689);
insert into Aircraft (aid, aname, cruisingrange) values (7, 'Air China', 6743);
insert into Aircraft (aid, aname, cruisingrange) values (8, 'Jet Airways', 6375);
insert into Aircraft (aid, aname, cruisingrange) values (9, 'Boeing', 3602);
insert into Aircraft (aid, aname, cruisingrange) values (10, 'Emirates', 1502);
insert into Aircraft (aid, aname, cruisingrange) values (11, 'United', 3315);
insert into Aircraft (aid, aname, cruisingrange) values (12, 'Jet Airways', 9666);
insert into Aircraft (aid, aname, cruisingrange) values (13, 'United', 7782);
insert into Aircraft (aid, aname, cruisingrange) values (14, 'Air China', 516);
insert into Aircraft (aid, aname, cruisingrange) values (15, 'Air India', 5405);
insert into Aircraft (aid, aname, cruisingrange) values (16, 'Air China', 2448);
insert into Aircraft (aid, aname, cruisingrange) values (17, 'Air India', 245);
insert into Aircraft (aid, aname, cruisingrange) values (18, 'Boeing', 8001);
insert into Aircraft (aid, aname, cruisingrange) values (19, 'Air China', 2791);
insert into Aircraft (aid, aname, cruisingrange) values (20, 'Jet Blue', 9110);
insert into Aircraft (aid, aname, cruisingrange) values (21, 'Air India', 1482);
insert into Aircraft (aid, aname, cruisingrange) values (22, 'Jet Blue', 6988);
insert into Aircraft (aid, aname, cruisingrange) values (23, 'Jet Airways', 2910);
insert into Aircraft (aid, aname, cruisingrange) values (24, 'Jet Airways', 609);
insert into Aircraft (aid, aname, cruisingrange) values (25, 'Jet Blue', 676);
insert into Aircraft (aid, aname, cruisingrange) values (26, 'Boeing', 5888);
insert into Aircraft (aid, aname, cruisingrange) values (27, 'Jet Blue', 6065);
insert into Aircraft (aid, aname, cruisingrange) values (28, 'Emirates', 3075);
insert into Aircraft (aid, aname, cruisingrange) values (29, 'United', 3799);
insert into Aircraft (aid, aname, cruisingrange) values (30, 'Jet Airways', 7371);
insert into Aircraft (aid, aname, cruisingrange) values (31, 'Boeing', 4836);
insert into Aircraft (aid, aname, cruisingrange) values (32, 'Boeing', 4708);
insert into Aircraft (aid, aname, cruisingrange) values (33, 'Emirates', 8619);
insert into Aircraft (aid, aname, cruisingrange) values (34, 'Air India', 8386);
insert into Aircraft (aid, aname, cruisingrange) values (35, 'Jet Blue', 5642);
insert into Aircraft (aid, aname, cruisingrange) values (36, 'Jet Airways', 7576);
insert into Aircraft (aid, aname, cruisingrange) values (37, 'Boeing', 484);
insert into Aircraft (aid, aname, cruisingrange) values (38, 'Jet Airways', 4303);
insert into Aircraft (aid, aname, cruisingrange) values (39, 'Jet Airways', 2895);
insert into Aircraft (aid, aname, cruisingrange) values (40, 'Jet Airways', 1983);
insert into Aircraft (aid, aname, cruisingrange) values (41, 'Jet Airways', 7393);
insert into Aircraft (aid, aname, cruisingrange) values (42, 'Air India', 4113);
insert into Aircraft (aid, aname, cruisingrange) values (43, 'United', 8059);
insert into Aircraft (aid, aname, cruisingrange) values (44, 'Boeing', 1771);
insert into Aircraft (aid, aname, cruisingrange) values (45, 'Air China', 587);
insert into Aircraft (aid, aname, cruisingrange) values (46, 'Jet Blue', 2803);
insert into Aircraft (aid, aname, cruisingrange) values (47, 'Emirates', 6334);
insert into Aircraft (aid, aname, cruisingrange) values (48, 'Jet Blue', 4334);
insert into Aircraft (aid, aname, cruisingrange) values (49, 'Jet Airways', 1628);
insert into Aircraft (aid, aname, cruisingrange) values (50, 'Jet Airways', 7366);
insert into Aircraft (aid, aname, cruisingrange) values (51, 'Jet Blue', 1600);
insert into Aircraft (aid, aname, cruisingrange) values (52, 'Emirates', 4136);
insert into Aircraft (aid, aname, cruisingrange) values (53, 'Jet Airways', 1993);
insert into Aircraft (aid, aname, cruisingrange) values (54, 'Air China', 4415);
insert into Aircraft (aid, aname, cruisingrange) values (55, 'Boeing', 5743);
insert into Aircraft (aid, aname, cruisingrange) values (56, 'Air China', 5433);
insert into Aircraft (aid, aname, cruisingrange) values (57, 'United', 8305);
insert into Aircraft (aid, aname, cruisingrange) values (58, 'Jet Blue', 4527);
insert into Aircraft (aid, aname, cruisingrange) values (59, 'Air India', 7410);
insert into Aircraft (aid, aname, cruisingrange) values (60, 'United', 2345);
insert into Aircraft (aid, aname, cruisingrange) values (61, 'Air China', 458);
insert into Aircraft (aid, aname, cruisingrange) values (62, 'Jet Airways', 2767);
insert into Aircraft (aid, aname, cruisingrange) values (63, 'Jet Blue', 5141);
insert into Aircraft (aid, aname, cruisingrange) values (64, 'United', 970);
insert into Aircraft (aid, aname, cruisingrange) values (65, 'United', 2080);
insert into Aircraft (aid, aname, cruisingrange) values (66, 'United', 8566);
insert into Aircraft (aid, aname, cruisingrange) values (67, 'Jet Blue', 5086);
insert into Aircraft (aid, aname, cruisingrange) values (68, 'Emirates', 3910);
insert into Aircraft (aid, aname, cruisingrange) values (69, 'Boeing', 9068);
insert into Aircraft (aid, aname, cruisingrange) values (70, 'United', 6656);
insert into Aircraft (aid, aname, cruisingrange) values (71, 'Air India', 9596);
insert into Aircraft (aid, aname, cruisingrange) values (72, 'Jet Blue', 1460);
insert into Aircraft (aid, aname, cruisingrange) values (73, 'Jet Airways', 8310);
insert into Aircraft (aid, aname, cruisingrange) values (74, 'Jet Blue', 2939);
insert into Aircraft (aid, aname, cruisingrange) values (75, 'United', 8312);
insert into Aircraft (aid, aname, cruisingrange) values (76, 'Air India', 1435);
insert into Aircraft (aid, aname, cruisingrange) values (77, 'Air China', 6326);
insert into Aircraft (aid, aname, cruisingrange) values (78, 'Boeing', 4156);
insert into Aircraft (aid, aname, cruisingrange) values (79, 'Jet Blue', 3144);
insert into Aircraft (aid, aname, cruisingrange) values (80, 'Air India', 3532);
insert into Aircraft (aid, aname, cruisingrange) values (81, 'Emirates', 8321);
insert into Aircraft (aid, aname, cruisingrange) values (82, 'Air India', 6759);
insert into Aircraft (aid, aname, cruisingrange) values (83, 'Air China', 8358);
insert into Aircraft (aid, aname, cruisingrange) values (84, 'Air China', 9474);
insert into Aircraft (aid, aname, cruisingrange) values (85, 'United', 5604);
insert into Aircraft (aid, aname, cruisingrange) values (86, 'Jet Airways', 7593);
insert into Aircraft (aid, aname, cruisingrange) values (87, 'Air India', 1863);
insert into Aircraft (aid, aname, cruisingrange) values (88, 'Boeing', 6868);
insert into Aircraft (aid, aname, cruisingrange) values (89, 'United', 2011);
insert into Aircraft (aid, aname, cruisingrange) values (90, 'Jet Airways', 8365);
insert into Aircraft (aid, aname, cruisingrange) values (91, 'Jet Airways', 7401);
insert into Aircraft (aid, aname, cruisingrange) values (92, 'Air India', 1585);
insert into Aircraft (aid, aname, cruisingrange) values (93, 'Jet Airways', 1258);
insert into Aircraft (aid, aname, cruisingrange) values (94, 'United', 2357);
insert into Aircraft (aid, aname, cruisingrange) values (95, 'Air India', 6559);
insert into Aircraft (aid, aname, cruisingrange) values (96, 'Boeing', 3124);
insert into Aircraft (aid, aname, cruisingrange) values (97, 'Air China', 3196);
insert into Aircraft (aid, aname, cruisingrange) values (98, 'Jet Airways', 4739);
insert into Aircraft (aid, aname, cruisingrange) values (99, 'Jet Airways', 5004);
insert into Aircraft (aid, aname, cruisingrange) values (100, 'Air India', 3171);
